// scripts/generate-feed.mjs
import { mkdir, readFile, writeFile } from 'fs/promises'
import path from 'path'

const FEED_PATH = 'public/ai-tools-feed.json'

function getOfficialLink(toolName) {
  const links = {
    'Claude 3': 'https://claude.ai',
    'Google Gemini': 'https://gemini.google.com',
    'Perplexity AI': 'https://perplexity.ai',
    'Jasper AI': 'https://jasper.ai',
    'Midjourney': 'https://midjourney.com',
    'Runway ML': 'https://runwayml.com',
    'Stable Diffusion': 'https://stability.ai',
    'Mistral AI': 'https://mistral.ai',
    'Cohere Command R+': 'https://cohere.com',
    'IBM Watsonx': 'https://watsonx.ai',
    'Salesforce Agentforce': 'https://salesforce.com/products/agentforce',
    'Amazon Q': 'https://aws.amazon.com/q',
    'Hugging Face': 'https://huggingface.co',
    'Replit Ghostwriter': 'https://replit.com/ai',
    'Notion AI': 'https://notion.so/product/ai'
  }
  return links[toolName] || '#'
}

function getLogoUrl(toolName) {
  // Using local SVG logos to avoid external 404 errors
  const logos = {
    'Concierge': '/Concierge.svg',
    'Plai': '/Plai.svg',
    'Claude 3': '/logos/claude.svg',
    'Google Gemini': '/logos/gemini.svg',
    'Perplexity AI': '/logos/perplexity.svg',
    'Jasper AI': '/logos/jasper.svg',
    'Midjourney': '/logos/midjourney.svg',
    'Runway ML': '/logos/runway.svg',
    'Stable Diffusion': '/logos/stable-diffusion.svg',
    'Mistral AI': '/logos/mistral.svg',
    'Cohere Command R+': '/logos/cohere.svg',
    'IBM Watsonx': '/logos/ibm-watsonx.svg',
    'Salesforce Agentforce': '/logos/salesforce.svg',
    'Amazon Q': '/logos/amazon-q.svg',
    'Hugging Face': '/logos/huggingface.svg',
    'Replit Ghostwriter': '/logos/replit.svg',
    'Notion AI': '/logos/notion.svg',
    'Microsoft Copilot': '/logos/microsoft-copilot.svg',
    'ChatGPT': '/logos/chatgpt.svg'
  }
  return logos[toolName] || ''
}

function dedupeByName(list) {
  const m = new Map()
  for (const item of list) {
    if (!item?.name) continue
    m.set(item.name.toLowerCase(), item)
  }
  return Array.from(m.values())
}

async function run() {
  let existingTools = []
  try {
    const raw = await readFile(FEED_PATH, 'utf8')
    const parsed = JSON.parse(raw)
    if (Array.isArray(parsed)) {
      existingTools = parsed
    } else if (Array.isArray(parsed?.tools)) {
      existingTools = parsed.tools
    }
  } catch {
    console.warn('No existing feed found, starting from curated defaults')
  }

  const curated = [
    // AI-COMPASS - hardcoded to ensure consistency
    {
      name: 'AI-COMPASS',
      type: 'internal',
      primaryPurpose: 'AI and digital solution discovery platform',
      targetUsers: 'All Sanofians',
      technology: 'GenAI and Knowledge Graph',
      bestUseCase: 'Comparing, aligning, and reusing existing digital and AI initiatives across the enterprise',
      cost: 'For Sanofi internal use',
      realTimeWebSearch: true,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://sonnil.github.io/AI-Compass/?demo=true',
      salesDescription: 'AI-COMPASS accelerates innovation by centralizing visibility across Sanofi\'s digital and AI ecosystem. It empowers every Sanofian to discover, compare, and connect with existing solutions, reducing duplication, enhancing collaboration, and driving smarter, faster decisions enterprise-wide.',
      tags: ['internal', 'ai', 'digital-innovation', 'knowledge-management', 'genai']
    },
    {
      name: 'Plai',
      type: 'internal',
      primaryPurpose: 'Snackable AI platform for real-time business intelligence',
      targetUsers: 'All Sanofians (20,000+ daily users)',
      technology: 'AI-driven analytics and insights platform',
      bestUseCase: 'Real-time data dashboards, AI-driven insights, 360° business view',
      cost: 'Company-wide platform',
      realTimeWebSearch: true,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://plai.sanofi.com',
      projectStatus: 'Production',
      deploymentPhase: 'Fully Operational - 20,000+ users',
      statusLastUpdated: '2025-01',
      salesDescription: 'Plai empowers 20,000 Sanofians daily with AI-driven, real-time business intelligence that transforms decision-making from quarterly reviews to 24/7 strategic insights.',
      tags: ['internal', 'snackable-ai', 'analytics', 'real-time', 'business-intelligence']
    },
    {
      name: 'Concierge',
      type: 'internal',
      primaryPurpose: 'AI assistant for employee productivity and support',
      targetUsers: 'All Sanofi employees',
      technology: 'GenAI/LLM Platform',
      bestUseCase: 'Knowledge search, document creation, meeting scheduling, email management',
      cost: 'Company-wide deployment',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: true,
      accessLink: 'https://concierge.sanofi.com',
      projectStatus: 'Production',
      deploymentPhase: 'Live - Company-wide deployment',
      statusLastUpdated: '2025-01',
      salesDescription: 'Concierge is Sanofi\'s AI assistant that helps employees be more productive by finding information quickly, managing meetings, creating documents, and navigating Sanofi\'s digital ecosystem.',
      tags: ['internal', 'ai-assistant', 'productivity', 'genai']
    },
    {
      name: 'BioAIM',
      type: 'internal',
      primaryPurpose: 'AI-driven drug discovery platform for Large Molecule Research',
      targetUsers: 'LMR scientists, Research teams',
      technology: 'AI/ML Platform for biologics',
      bestUseCase: 'Hit selection, lead optimization, candidate analysis',
      cost: 'R&D investment',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://bioaim.sanofi.com',
      projectStatus: 'Scaling',
      deploymentPhase: 'Scaling - Operationalizing platform',
      statusLastUpdated: '2025-01',
      salesDescription: 'BioAIM is the first fully unified and integrated drug discovery platform for Large Molecule Research scientists, improving candidate quality while reducing discovery time and risk.',
      tags: ['internal', 'drug-discovery', 'research', 'ai-ml']
    },
    {
      name: 'TieGPT',
      type: 'internal',
      primaryPurpose: 'Target identification and validation',
      targetUsers: 'Research teams',
      technology: 'GenAI/LLM',
      bestUseCase: 'Target identification in drug discovery',
      cost: 'R&D budget',
      realTimeWebSearch: true,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://tiegpt.sanofi.com',
      projectStatus: 'Development',
      deploymentPhase: 'In Development',
      statusLastUpdated: '2025-01',
      salesDescription: 'TieGPT accelerates target identification and validation in early drug discovery through AI-powered analysis of biological connections and pathways.',
      tags: ['internal', 'research', 'target-identification', 'genai']
    },
    {
      name: 'MUSE',
      type: 'internal',
      primaryPurpose: 'Clinical trial patient recruitment optimization',
      targetUsers: 'Clinical Operations teams',
      technology: 'AI-powered patient matching',
      bestUseCase: 'Accelerating patient recruitment for clinical trials',
      cost: 'Clinical Development',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://muse.sanofi.com',
      projectStatus: 'Production',
      deploymentPhase: 'Recently Launched',
      statusLastUpdated: '2025-01',
      salesDescription: 'MUSE is an advanced AI-powered tool designed to accelerate and improve the development of new medicines by optimizing patient recruitment for clinical trials.',
      tags: ['internal', 'clinical-trials', 'patient-recruitment', 'ai']
    },
    {
      name: 'Plai ClinOps',
      type: 'internal',
      primaryPurpose: 'Clinical operations analytics and insights',
      targetUsers: 'Clinical Operations teams',
      technology: 'AI analytics platform',
      bestUseCase: 'Clinical trial performance monitoring and optimization',
      cost: 'Clinical Development',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://plai.sanofi.com/clinops',
      projectStatus: 'Production',
      deploymentPhase: 'In Production',
      statusLastUpdated: '2025-01',
      salesDescription: 'Plai ClinOps provides real-time analytics and AI-driven insights for clinical trial operations, enabling faster decision-making and performance optimization.',
      tags: ['internal', 'clinical-operations', 'analytics', 'plai-module']
    },
    {
      name: 'GenAI CSR',
      type: 'internal',
      primaryPurpose: 'Clinical Study Report generation',
      targetUsers: 'Clinical Development, Regulatory teams',
      technology: 'GenAI document generation',
      bestUseCase: 'Accelerating CSR writing and review',
      cost: 'Clinical Development',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://genaicsr.sanofi.com',
      projectStatus: 'Development',
      deploymentPhase: 'Estimated: MVP',
      statusLastUpdated: '2025-01',
      salesDescription: 'GenAI CSR accelerates the creation of Clinical Study Reports through AI-powered document generation, reducing writing time while maintaining compliance.',
      tags: ['internal', 'clinical-development', 'document-generation', 'genai']
    },
    {
      name: 'SimplY Plai',
      type: 'internal',
      primaryPurpose: 'Supply chain management analytics',
      targetUsers: 'Supply Chain teams',
      technology: 'AI analytics platform',
      bestUseCase: 'Supply chain visibility and optimization',
      cost: 'Manufacturing & Supply',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://plai.sanofi.com/supply',
      projectStatus: 'Production',
      deploymentPhase: 'In Production',
      statusLastUpdated: '2025-01',
      salesDescription: 'SimplY Plai delivers AI-powered supply chain analytics and insights, enabling real-time visibility and optimization across the manufacturing and supply network.',
      tags: ['internal', 'supply-chain', 'analytics', 'plai-module']
    },
    {
      name: 'GenAIR MSAT',
      type: 'internal',
      primaryPurpose: 'Manufacturing science and technology support',
      targetUsers: 'Manufacturing teams',
      technology: 'GenAI platform',
      bestUseCase: 'Manufacturing process optimization',
      cost: 'Manufacturing & Supply',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://genair.sanofi.com',
      projectStatus: 'Development',
      deploymentPhase: 'Estimated: Pilot',
      statusLastUpdated: '2025-01',
      salesDescription: 'GenAIR MSAT applies generative AI to manufacturing science and technology, optimizing production processes and solving complex manufacturing challenges.',
      tags: ['internal', 'manufacturing', 'process-optimization', 'genai']
    },
    {
      name: 'MedIS',
      type: 'internal',
      primaryPurpose: 'Medical insights engine',
      targetUsers: 'Medical & R&D teams',
      technology: 'GenAI Platform',
      bestUseCase: 'Medical insights and compliance',
      cost: 'For Medical/R&D',
      realTimeWebSearch: false,
      codeGeneration: true,
      imageGeneration: false,
      accessLink: 'https://medinsights.sanofi.com',
      projectStatus: 'Production',
      deploymentPhase: 'In Production',
      statusLastUpdated: '2025-01',
      salesDescription: 'MedIS delivers AI-powered medical insights to support evidence-based decision making while ensuring compliance with medical and regulatory requirements.',
      tags: ['internal', 'medical', 'insights']
    },
    {
      name: 'DAI Vinci',
      type: 'internal',
      primaryPurpose: 'HCP engagement optimization',
      targetUsers: 'Commercial teams',
      technology: 'AI/ML platform',
      bestUseCase: 'Personalized HCP engagement',
      cost: 'Commercial Operations',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://daivinci.sanofi.com',
      projectStatus: 'Production',
      deploymentPhase: 'In Production',
      statusLastUpdated: '2025-01',
      salesDescription: 'DAI Vinci optimizes healthcare provider engagement through AI-powered personalization, delivering the right content through the right channels at the right time.',
      tags: ['internal', 'commercial', 'hcp-engagement', 'ai-ml']
    },
    {
      name: 'Turing',
      type: 'internal',
      primaryPurpose: 'Next best action recommendations for HCP engagement',
      targetUsers: 'Commercial teams',
      technology: 'ML recommendation engine',
      bestUseCase: 'Optimizing HCP communications and engagement',
      cost: 'Commercial Operations',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://turing.sanofi.com',
      projectStatus: 'Production',
      deploymentPhase: 'In Production',
      statusLastUpdated: '2025-01',
      salesDescription: 'Turing provides commercial teams with AI-powered recommendations for the next best action: what to communicate to HCPs, when to communicate it, and through which channel.',
      tags: ['internal', 'commercial', 'next-best-action', 'ml']
    },
    {
      name: 'PRISM',
      type: 'internal',
      primaryPurpose: 'Commercial analytics and insights',
      targetUsers: 'Commercial teams',
      technology: 'AI analytics platform',
      bestUseCase: 'Market and performance analytics',
      cost: 'Commercial Operations',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://prism.sanofi.com',
      projectStatus: 'Production',
      deploymentPhase: 'In Production',
      statusLastUpdated: '2025-01',
      salesDescription: 'PRISM delivers AI-powered commercial analytics and insights, enabling data-driven decision making for market strategy and performance optimization.',
      tags: ['internal', 'commercial', 'analytics', 'ai']
    },
    {
      name: 'AccelRare',
      type: 'internal',
      primaryPurpose: 'Rare disease patient finding',
      targetUsers: 'Medical, Commercial teams',
      technology: 'AI/ML platform',
      bestUseCase: 'Accelerating rare disease diagnosis',
      cost: 'Medical Affairs',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://accelrare.sanofi.com',
      projectStatus: 'Development',
      deploymentPhase: 'Estimated: Pilot',
      statusLastUpdated: '2025-01',
      salesDescription: 'AccelRare uses AI to accelerate rare disease diagnosis by identifying patterns in patient data that may indicate undiagnosed rare conditions.',
      tags: ['internal', 'rare-disease', 'patient-finding', 'ai-ml']
    },
    {
      name: 'Artemis',
      type: 'internal',
      primaryPurpose: 'Patient safety and pharmacovigilance',
      targetUsers: 'Safety teams',
      technology: 'AI/ML platform',
      bestUseCase: 'Adverse event processing and analysis',
      cost: 'Global Pharmacovigilance',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://artemis.sanofi.com',
      projectStatus: 'Production',
      deploymentPhase: 'In Production',
      statusLastUpdated: '2025-01',
      salesDescription: 'Artemis enables cognitive automation for pharmacovigilance case management using AI/ML, improving efficiency and accuracy in patient safety monitoring.',
      tags: ['internal', 'pharmacovigilance', 'safety', 'ai-ml']
    },
    {
      name: 'Simple to Know',
      type: 'internal',
      primaryPurpose: 'Knowledge management and simplification',
      targetUsers: 'All Sanofi employees',
      technology: 'GenAI platform',
      bestUseCase: 'Simplifying complex information',
      cost: 'Company-wide platform',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://simple2know.sanofi.com',
      projectStatus: 'Development',
      deploymentPhase: 'Estimated: MVP',
      statusLastUpdated: '2025-01',
      salesDescription: 'Simple to Know uses AI to transform complex information into clear, accessible knowledge, supporting Sanofi\'s simplification initiative.',
      tags: ['internal', 'knowledge-management', 'simplification', 'genai']
    },
    {
      name: 'Mesh Explorer',
      type: 'internal',
      primaryPurpose: 'Data mesh exploration and visualization',
      targetUsers: 'Data teams, Business analysts',
      technology: 'AI-powered data visualization',
      bestUseCase: 'Data relationship discovery and exploration',
      cost: 'Digital & Data',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: true,
      accessLink: 'https://meshexplorer.sanofi.com',
      projectStatus: 'Development',
      deploymentPhase: 'Estimated: Pilot',
      statusLastUpdated: '2025-01',
      salesDescription: 'Mesh Explorer provides AI-powered visualization and exploration of Sanofi\'s data mesh, revealing hidden relationships and insights across data domains.',
      tags: ['internal', 'data-mesh', 'visualization', 'ai']
    },
    {
      name: 'Newton',
      type: 'internal',
      primaryPurpose: 'Manufacturing process optimization',
      targetUsers: 'Manufacturing teams',
      technology: 'AI/ML platform',
      bestUseCase: 'Process parameter optimization',
      cost: 'Manufacturing & Supply',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://newton.sanofi.com',
      projectStatus: 'Development',
      deploymentPhase: 'Estimated: MVP',
      statusLastUpdated: '2025-01',
      salesDescription: 'Newton applies AI/ML to manufacturing process optimization, identifying optimal parameters for quality, yield, and efficiency.',
      tags: ['internal', 'manufacturing', 'process-optimization', 'ai-ml']
    },
    {
      name: 'GenAI Content',
      type: 'internal',
      primaryPurpose: 'Marketing and commercial content generation',
      targetUsers: 'Marketing, Commercial teams',
      technology: 'GenAI platform',
      bestUseCase: 'Creating compliant marketing materials at scale',
      cost: 'Commercial Operations',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: true,
      accessLink: 'https://genaicontent.sanofi.com',
      projectStatus: 'Production',
      deploymentPhase: 'In Production',
      statusLastUpdated: '2025-01',
      salesDescription: 'GenAI Content accelerates the creation of compliant marketing and commercial materials through AI-powered content generation, enabling personalized engagement at scale.',
      tags: ['internal', 'marketing', 'content-generation', 'genai']
    },
    {
      name: 'AI Nurse Agent',
      type: 'internal',
      primaryPurpose: 'Patient support and engagement',
      targetUsers: 'Patients, Healthcare providers',
      technology: 'AI conversational agent',
      bestUseCase: '24/7 patient support and medication guidance',
      cost: 'Patient Services',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://ainurse.sanofi.com',
      projectStatus: 'Development',
      deploymentPhase: 'Estimated: Pilot',
      statusLastUpdated: '2025-01',
      salesDescription: 'AI Nurse Agent provides 24/7 patient support through conversational AI, answering questions about medications, side effects, and treatment adherence.',
      tags: ['internal', 'patient-support', 'conversational-ai', 'healthcare']
    },
    {
      name: 'NBI',
      type: 'internal',
      primaryPurpose: 'Nurse Bot Interface for patient engagement',
      targetUsers: 'Patients, Care coordinators',
      technology: 'AI chatbot platform',
      bestUseCase: 'Patient education and support',
      cost: 'Patient Services',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://nbi.sanofi.com',
      projectStatus: 'Development',
      deploymentPhase: 'Estimated: MVP',
      statusLastUpdated: '2025-01',
      salesDescription: 'NBI delivers personalized patient education and support through an intelligent chatbot interface, improving treatment adherence and patient outcomes.',
      tags: ['internal', 'patient-engagement', 'chatbot', 'education']
    },
    {
      name: 'ClinicalBERT',
      type: 'internal',
      primaryPurpose: 'Clinical data analysis and insights',
      targetUsers: 'Clinical Development, Medical teams',
      technology: 'Specialized LLM for clinical data',
      bestUseCase: 'Analyzing patient data and predicting clinical outcomes',
      cost: 'Clinical Development',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://clinicalbert.sanofi.com',
      projectStatus: 'Scaling',
      deploymentPhase: 'Scaling - Expanding use cases',
      statusLastUpdated: '2025-01',
      salesDescription: 'ClinicalBERT leverages specialized language models to analyze clinical trial data, predict patient outcomes, and accelerate evidence generation for better decision-making.',
      tags: ['internal', 'clinical-data', 'llm', 'analytics']
    },
    {
      name: 'BioMap',
      type: 'internal',
      primaryPurpose: 'Protein language model for biologics',
      targetUsers: 'Research teams, Biologics development',
      technology: 'Protein Language Model',
      bestUseCase: 'Protein structure prediction and optimization',
      cost: 'R&D investment',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://biomap.sanofi.com',
      projectStatus: 'Development',
      deploymentPhase: 'In Development',
      statusLastUpdated: '2025-01',
      salesDescription: 'BioMap uses protein language models to predict protein structures and optimize biologics development, accelerating the discovery of novel therapeutic candidates.',
      tags: ['internal', 'biologics', 'protein-modeling', 'ai']
    },
    {
      name: 'Search & Design (Aqemia)',
      type: 'internal',
      primaryPurpose: 'AI-powered molecular design',
      targetUsers: 'Chemistry teams, CMC',
      technology: 'AI molecular design platform',
      bestUseCase: 'Lead optimization and molecular design',
      cost: 'R&D investment',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://searchdesign.sanofi.com',
      projectStatus: 'Development',
      deploymentPhase: 'Estimated: Pilot',
      statusLastUpdated: '2025-01',
      salesDescription: 'Search & Design accelerates lead optimization through AI-powered molecular design, identifying optimal chemical structures with improved properties and manufacturability.',
      tags: ['internal', 'molecular-design', 'chemistry', 'ai']
    },
    {
      name: 'OneAI',
      type: 'internal',
      primaryPurpose: 'Enterprise AI platform for specialist use cases',
      targetUsers: 'Data scientists and AI developers',
      technology: 'AI/ML Development Platform',
      bestUseCase: 'Custom AI model development and deployment',
      cost: 'For AI/ML teams',
      realTimeWebSearch: false,
      codeGeneration: true,
      imageGeneration: false,
      accessLink: 'https://docs.sanofi.com/one-ai',
      salesDescription: 'OneAI is our enterprise AI development platform that accelerates the creation and deployment of custom AI solutions. It reduces AI development costs and time-to-value while ensuring governance and scalability.',
      tags: ['internal', 'ai-platform', 'ml-development', 'specialist-ai']
    },
    {
      name: 'AWS SageMaker',
      type: 'external',
      primaryPurpose: 'ML model development and deployment',
      targetUsers: 'Data scientists, ML engineers',
      technology: 'Cloud ML platform',
      bestUseCase: 'End-to-end ML workflow management',
      cost: 'Pay-per-use cloud service',
      realTimeWebSearch: false,
      codeGeneration: true,
      imageGeneration: false,
      accessLink: 'https://aws.amazon.com/sagemaker/',
      projectStatus: 'External Tool - Not Applicable',
      deploymentPhase: 'External Service',
      statusLastUpdated: '2025-01',
      salesDescription: 'AWS SageMaker provides end-to-end machine learning capabilities for building, training, and deploying models at scale with integrated development environments and automated workflows.',
      tags: ['external', 'cloud', 'ml-platform', 'aws']
    },
    {
      name: 'Microsoft Azure ML',
      type: 'external',
      primaryPurpose: 'Enterprise ML platform',
      targetUsers: 'Data scientists, ML engineers',
      technology: 'Cloud ML platform',
      bestUseCase: 'Enterprise ML lifecycle management',
      cost: 'Pay-per-use cloud service',
      realTimeWebSearch: false,
      codeGeneration: true,
      imageGeneration: false,
      accessLink: 'https://azure.microsoft.com/en-us/services/machine-learning/',
      projectStatus: 'External Tool - Not Applicable',
      deploymentPhase: 'External Service',
      statusLastUpdated: '2025-01',
      salesDescription: 'Azure ML provides enterprise-grade machine learning services with built-in security, compliance features, and seamless integration with Microsoft ecosystem for the full ML lifecycle.',
      tags: ['external', 'cloud', 'ml-platform', 'microsoft']
    },
    {
      name: 'Google Vertex AI',
      type: 'external',
      primaryPurpose: 'Unified ML platform',
      targetUsers: 'Data scientists, ML engineers',
      technology: 'Cloud ML platform',
      bestUseCase: 'Training and deploying ML models with foundation models',
      cost: 'Pay-per-use cloud service',
      realTimeWebSearch: false,
      codeGeneration: true,
      imageGeneration: true,
      accessLink: 'https://cloud.google.com/vertex-ai',
      projectStatus: 'External Tool - Not Applicable',
      deploymentPhase: 'External Service',
      statusLastUpdated: '2025-01',
      salesDescription: 'Google Vertex AI unifies Google Cloud\'s ML offerings with access to foundation models, enabling rapid development and deployment of AI solutions at enterprise scale.',
      tags: ['external', 'cloud', 'ml-platform', 'google']
    },
    {
      name: 'Databricks',
      type: 'external',
      primaryPurpose: 'Unified analytics and AI platform',
      targetUsers: 'Data engineers, Data scientists',
      technology: 'Lakehouse platform',
      bestUseCase: 'Big data processing and ML at scale',
      cost: 'Subscription-based cloud service',
      realTimeWebSearch: false,
      codeGeneration: true,
      imageGeneration: false,
      accessLink: 'https://www.databricks.com/',
      projectStatus: 'External Tool - Not Applicable',
      deploymentPhase: 'External Service',
      statusLastUpdated: '2025-01',
      salesDescription: 'Databricks provides a unified lakehouse platform that combines data warehousing and AI capabilities, enabling collaborative data science and ML at enterprise scale.',
      tags: ['external', 'data-platform', 'ml', 'analytics']
    },
    {
      name: 'Atomwise',
      type: 'external',
      primaryPurpose: 'AI-powered drug discovery',
      targetUsers: 'Research teams',
      technology: 'AI for molecular design',
      bestUseCase: 'Small molecule drug discovery and virtual screening',
      cost: 'Partnership/subscription',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://www.atomwise.com/',
      projectStatus: 'External Tool - Not Applicable',
      deploymentPhase: 'External Service',
      statusLastUpdated: '2025-01',
      salesDescription: 'Atomwise uses deep learning to predict molecular binding and design small molecules, dramatically reducing the time and cost of early-stage drug discovery.',
      tags: ['external', 'drug-discovery', 'ai', 'small-molecule']
    },
    {
      name: 'Insitro',
      type: 'external',
      primaryPurpose: 'Machine learning for drug development',
      targetUsers: 'Research teams',
      technology: 'ML platform with high-throughput biology',
      bestUseCase: 'Target discovery and validation',
      cost: 'Partnership/subscription',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://insitro.com/',
      projectStatus: 'External Tool - Not Applicable',
      deploymentPhase: 'External Service',
      statusLastUpdated: '2025-01',
      salesDescription: 'Insitro combines machine learning with high-throughput biology to transform drug discovery, using data-driven approaches to identify and validate novel therapeutic targets.',
      tags: ['external', 'drug-discovery', 'ml', 'biology']
    },
    {
      name: 'BenevolentAI',
      type: 'external',
      primaryPurpose: 'AI platform for drug discovery',
      targetUsers: 'Research teams',
      technology: 'AI knowledge graph',
      bestUseCase: 'Target identification and drug repurposing',
      cost: 'Partnership/subscription',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://www.benevolent.com/',
      projectStatus: 'External Tool - Not Applicable',
      deploymentPhase: 'External Service',
      statusLastUpdated: '2025-01',
      salesDescription: 'BenevolentAI\'s platform combines AI with biomedical knowledge graphs to discover novel drug targets and repurpose existing drugs, accelerating the path to new treatments.',
      tags: ['external', 'drug-discovery', 'ai', 'knowledge-graph']
    },
    {
      name: 'Schrodinger',
      type: 'external',
      primaryPurpose: 'Computational chemistry and molecular modeling',
      targetUsers: 'Chemistry teams, Research',
      technology: 'Physics-based molecular modeling',
      bestUseCase: 'Drug design and molecular simulation',
      cost: 'Software license',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://www.schrodinger.com/',
      projectStatus: 'External Tool - Not Applicable',
      deploymentPhase: 'External Service',
      statusLastUpdated: '2025-01',
      salesDescription: 'Schrodinger provides industry-leading computational chemistry software for drug design, combining physics-based modeling with AI to predict molecular properties and optimize candidates.',
      tags: ['external', 'computational-chemistry', 'molecular-modeling', 'drug-design']
    },
    {
      name: 'Insilico Medicine',
      type: 'external',
      primaryPurpose: 'AI-driven drug discovery platform',
      targetUsers: 'Research teams',
      technology: 'Generative AI for drug design',
      bestUseCase: 'End-to-end AI drug discovery',
      cost: 'Partnership/subscription',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://insilico.com/',
      projectStatus: 'External Tool - Not Applicable',
      deploymentPhase: 'External Service',
      statusLastUpdated: '2025-01',
      salesDescription: 'Insilico Medicine uses generative AI and reinforcement learning for end-to-end drug discovery, from target identification to molecular design and clinical candidate selection.',
      tags: ['external', 'drug-discovery', 'generative-ai', 'end-to-end']
    },
    {
      name: 'Recursion Pharmaceuticals',
      type: 'external',
      primaryPurpose: 'AI-powered drug discovery with cellular imaging',
      targetUsers: 'Research teams',
      technology: 'ML with high-content imaging',
      bestUseCase: 'Phenotypic drug discovery',
      cost: 'Partnership',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://www.recursion.com/',
      projectStatus: 'External Tool - Not Applicable',
      deploymentPhase: 'External Service',
      statusLastUpdated: '2025-01',
      salesDescription: 'Recursion combines high-content cellular imaging with machine learning to discover new drugs through phenotypic screening, identifying novel mechanisms of action.',
      tags: ['external', 'drug-discovery', 'imaging', 'phenotypic-screening']
    },
    {
      name: 'Medidata',
      type: 'external',
      primaryPurpose: 'Clinical trial management platform',
      targetUsers: 'Clinical Operations teams',
      technology: 'Cloud-based clinical platform',
      bestUseCase: 'End-to-end clinical trial management',
      cost: 'Enterprise subscription',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://www.medidata.com/',
      projectStatus: 'External Tool - Not Applicable',
      deploymentPhase: 'External Service',
      statusLastUpdated: '2025-01',
      salesDescription: 'Medidata\'s unified platform combines data, analytics, and AI to optimize clinical trials from design through execution, improving trial efficiency and data quality.',
      tags: ['external', 'clinical-trials', 'platform', 'analytics']
    },
    {
      name: 'Veeva',
      type: 'external',
      primaryPurpose: 'Clinical and regulatory cloud solutions',
      targetUsers: 'Clinical Operations, Regulatory teams',
      technology: 'Cloud platform',
      bestUseCase: 'Clinical data and document management',
      cost: 'Enterprise subscription',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://www.veeva.com/',
      projectStatus: 'External Tool - Not Applicable',
      deploymentPhase: 'External Service',
      statusLastUpdated: '2025-01',
      salesDescription: 'Veeva\'s unified clinical and regulatory suite streamlines trial execution and regulatory submissions with integrated applications for study startup, TMF, CTMS, and eTMF.',
      tags: ['external', 'clinical-operations', 'regulatory', 'cloud']
    },
    {
      name: 'Oracle Clinical',
      type: 'external',
      primaryPurpose: 'Clinical trial data management',
      targetUsers: 'Clinical Data Management teams',
      technology: 'Clinical data platform',
      bestUseCase: 'EDC and clinical data management',
      cost: 'Enterprise license',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://www.oracle.com/life-sciences/clinical-research/',
      projectStatus: 'External Tool - Not Applicable',
      deploymentPhase: 'External Service',
      statusLastUpdated: '2025-01',
      salesDescription: 'Oracle Clinical provides comprehensive clinical data management solutions including EDC, CDMS, and safety reporting to support efficient and compliant clinical trials.',
      tags: ['external', 'clinical-data', 'edc', 'oracle']
    },
    {
      name: 'Saama',
      type: 'external',
      primaryPurpose: 'Clinical analytics and AI platform',
      targetUsers: 'Clinical Operations, Data teams',
      technology: 'AI-powered clinical analytics',
      bestUseCase: 'Clinical trial optimization and insights',
      cost: 'Subscription-based',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://www.saama.com/',
      projectStatus: 'External Tool - Not Applicable',
      deploymentPhase: 'External Service',
      statusLastUpdated: '2025-01',
      salesDescription: 'Saama\'s AI-powered platform delivers real-time clinical trial analytics and insights, enabling proactive decision-making and trial optimization across the development lifecycle.',
      tags: ['external', 'clinical-analytics', 'ai', 'optimization']
    },
    {
      name: 'Cognizant Shared Investigator Platform',
      type: 'external',
      primaryPurpose: 'Site and investigator management',
      targetUsers: 'Clinical Operations teams',
      technology: 'Cloud platform',
      bestUseCase: 'Site selection and management',
      cost: 'Subscription-based',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://www.cognizant.com/us/en/life-sciences',
      projectStatus: 'External Tool - Not Applicable',
      deploymentPhase: 'External Service',
      statusLastUpdated: '2025-01',
      salesDescription: 'Cognizant\'s Shared Investigator Platform streamlines site selection and management through data-driven insights, improving site performance and patient recruitment.',
      tags: ['external', 'site-management', 'clinical-operations', 'platform']
    },
    {
      name: 'AspenTech',
      type: 'external',
      primaryPurpose: 'Process optimization software',
      targetUsers: 'Manufacturing, Process Engineering teams',
      technology: 'Process simulation and optimization',
      bestUseCase: 'Manufacturing process optimization',
      cost: 'Software license',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://www.aspentech.com/',
      projectStatus: 'External Tool - Not Applicable',
      deploymentPhase: 'External Service',
      statusLastUpdated: '2025-01',
      salesDescription: 'AspenTech provides industry-leading process optimization software that uses AI and advanced analytics to maximize manufacturing efficiency, quality, and sustainability.',
      tags: ['external', 'manufacturing', 'process-optimization', 'simulation']
    },
    {
      name: 'Quartic.ai',
      type: 'external',
      primaryPurpose: 'Manufacturing intelligence platform',
      targetUsers: 'Manufacturing teams',
      technology: 'AI/ML for manufacturing',
      bestUseCase: 'Real-time manufacturing optimization',
      cost: 'Subscription-based',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://quartic.ai/',
      projectStatus: 'External Tool - Not Applicable',
      deploymentPhase: 'External Service',
      statusLastUpdated: '2025-01',
      salesDescription: 'Quartic.ai delivers AI-powered manufacturing intelligence that provides real-time insights and recommendations to optimize production efficiency and product quality.',
      tags: ['external', 'manufacturing', 'ai', 'real-time-optimization']
    },
    {
      name: 'Bigfinite',
      type: 'external',
      primaryPurpose: 'GMP manufacturing intelligence',
      targetUsers: 'Manufacturing, Quality teams',
      technology: 'AI for pharma manufacturing',
      bestUseCase: 'Batch release and quality optimization',
      cost: 'Subscription-based',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://www.bigfinite.com/',
      projectStatus: 'External Tool - Not Applicable',
      deploymentPhase: 'External Service',
      statusLastUpdated: '2025-01',
      salesDescription: 'Bigfinite specializes in AI-powered manufacturing intelligence for GMP environments, accelerating batch release and optimizing quality through predictive analytics.',
      tags: ['external', 'manufacturing', 'gmp', 'quality']
    },
    {
      name: 'Tableau',
      type: 'external',
      primaryPurpose: 'Data visualization and analytics',
      targetUsers: 'Business analysts, Data teams',
      technology: 'BI and visualization platform',
      bestUseCase: 'Interactive dashboards and data exploration',
      cost: 'Subscription-based',
      realTimeWebSearch: false,
      codeGeneration: false,
      imageGeneration: false,
      accessLink: 'https://www.tableau.com/',
      projectStatus: 'External Tool - Not Applicable',
      deploymentPhase: 'External Service',
      statusLastUpdated: '2025-01',
      salesDescription: 'Tableau provides powerful data visualization and business intelligence capabilities, enabling users to create interactive dashboards and explore data insights through intuitive visual analytics.',
      tags: ['external', 'data-visualization', 'bi', 'analytics']
    },
    {
      name: 'OpenAI',
      type: 'external',
      primaryPurpose: 'Generative AI and LLM services',
      targetUsers: 'Developers, AI teams',
      technology: 'GenAI/LLM API',
      bestUseCase: 'Natural language processing, content generation, code assistance',
      cost: 'API usage-based pricing',
      realTimeWebSearch: false,
      codeGeneration: true,
      imageGeneration: true,
      accessLink: 'https://openai.com/',
      projectStatus: 'External Tool - Not Applicable',
      deploymentPhase: 'External Service',
      statusLastUpdated: '2025-01',
      salesDescription: 'OpenAI provides state-of-the-art generative AI models including GPT-4, enabling advanced natural language understanding, content generation, and code assistance capabilities.',
      tags: ['external', 'genai', 'llm', 'api']
    }
  ]

  const normalized = dedupeByName(curated).map(tool => {
  const curatedLogo = getLogoUrl(tool.name)
  const logoUrl = curatedLogo || tool.logoUrl
    const accessLink = tool.accessLink || getOfficialLink(tool.name)
    const tags = Array.isArray(tool.tags) ? tool.tags : []
    const type = tool.type || (tags.includes('internal') ? 'internal' : 'external')
    
    // Generate a unique ID from the tool name
    const id = tool.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
    
    return {
      ...tool,
      id,
      ...(logoUrl ? { logoUrl } : {}),
      ...(accessLink ? { accessLink } : {}),
      tags,
      type
    }
  })

  const outDir = path.dirname(FEED_PATH)
  await mkdir(outDir, { recursive: true })
  const output = {
    lastUpdated: new Date().toISOString(),
    totalTools: normalized.length,
    tools: normalized
  }
  await writeFile(FEED_PATH, JSON.stringify(output, null, 2))
  console.log(`Wrote ${normalized.length} tools → ${FEED_PATH}`)
}

run().catch(e => { console.error(e); process.exit(1) })
