export interface Tool {
  id: string;
  name: string;
  type: 'internal' | 'external';
  primaryPurpose: string;
  description?: string;
  salesDescription?: string;
  url?: string;
  features?: string[];
  tags: string[];
  capabilities?: {
    textGeneration?: boolean;
    codeGeneration?: boolean;
    imageGeneration?: boolean;
    dataAnalysis?: boolean;
    realTimeSearch?: boolean;
    documentAnalysis?: boolean;
    chat?: boolean;
    vision?: boolean;
  };
  access?: 'open' | 'request' | 'paid';
  contact?: string;
  owner?: string;
  logoUrl?: string;
  generalKnowledge?: boolean;
  targetUsers?: string;
  accessLink?: string;
  trainingLink?: string;
  supportLink?: string;
  documentationLink?: string;
  modules?: string;
  accessToSanofiSystems?: boolean | string;
  meetingScheduling?: boolean | string;
  emailManagement?: boolean | string;
  peopleSearch?: boolean | string;
  documentCreation?: boolean | string;
  knowledgeBase?: boolean | string;
  qualipsoAccess?: boolean | string;
  oneSupportTickets?: boolean | string;
  scientificLiterature?: boolean | string;
  patentAnalysis?: boolean | string;
  chemicalStructure?: boolean | string;
  dataViz?: boolean | string;
  predictiveAnalytics?: boolean | string;
  office365Integration?: boolean | string;
  excelDataAnalysis?: boolean | string;
  pptCreation?: boolean | string;
  realTimeWebSearch?: boolean | string;
  imageGeneration?: boolean | string;
  diagramCreation?: boolean | string;
  complianceAwareness?: boolean | string;
  trainingRequired?: string;
  cost?: string;
  bestUseCase?: string;
  technology?: string;
  projectStatus?: string;
  deploymentPhase?: string;
  statusLastUpdated?: string;
}

